Implement Convertor
NJUPT-SAST-Cpp/SAST-Evento-Desktop pull request #1
Opened 2023-08-17 05:47 UTC by ArcticLampyrid

WIP
Not ready for review or merging

2023-08-17 06:41 UTC, ArcticLampyrid commented
what is `src/domain/entity/department.h` used for?
@Serein207

2023-08-17 06:49 UTC, Serein207 commented
管理端创建活动时需要选择部门，需要展示全部的department，department作为DeaprementModel的元素

2023-08-17 06:49 UTC, Serein207 commented
> what is `src/domain/entity/department.h` used for? @Serein207

管理端创建活动时需要选择部门，需要展示全部的department，department作为DeaprementModel的元素

2023-08-17 07:40 UTC, ArcticLampyrid commented
https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/blob/bacc54d1a36854f106c8ec93a7977db6d0914437/src/domain/entity/user.h#L14C18-L14C18

另外，User 中的 link 是指？看了下飞书上的文档，没看到相关字段

2023-08-17 08:00 UTC, Serein207 commented
> > 管理端创建活动时需要选择部门，需要展示全部的department，department作为DeaprementModel的元素
> 
> 我看到很多地方的 department(s) 都使用了 string / string_list，需要修改吗

entity中表示由list组合而成的字符串，DTO中的是QStringList，list都命名为departments，entity都命名为department

2023-08-17 08:01 UTC, Serein207 commented
> https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/blob/bacc54d1a36854f106c8ec93a7977db6d0914437/src/domain/entity/user.h#L14
> 
> 另外，User 中的 link 是指？看了下飞书上的文档，没看到相关字段

User的数据结构未定，关于它的convertor先不写，link是个人信息的“友链”

2023-08-17 13:19 UTC, Serein207 commented
关注一下飞书文档，`entity/schedule` 的数据结构改了，转换格式旁边有注释

2023-08-21 16:43 UTC, Serein207 requested changes

2023-08-21 16:43 UTC, Serein207 commented on src/include/convertor.h
> +            getFirstImageUrl(e.id)
Schedule convertor总是返回 `std::vector` ，这里做关于它的特化就行了

2023-08-21 18:02 UTC, ArcticLampyrid commented on src/include/convertor.h
> +            getFirstImageUrl(e.id)
> Schedule convertor总是返回 `std::vector` ，这里做关于它的特化就行了

所有 `std::vector` 被统一支持

https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/blob/982bd43d1861b838092cec1784c7587da059880a/src/include/convertor.h#L47-L48

2023-08-21 18:05 UTC, Serein207 commented on src/include/convertor.h
> +            getFirstImageUrl(e.id)
这里Schedule涉及拆分，可能会出现一个DTO返回多个entity的情况

2023-08-21 19:01 UTC, ArcticLampyrid commented on src/include/convertor.h
> +            // check 字面意识指是否签到，但是这里的 isChecked 指是否已参加？
need to confirm.

2023-08-21 19:01 UTC, Serein207 commented on src/include/convertor.h
> +            0 /* FIXME: cannot get feedback id from `DTO_Feedback` */,
没事，DTO_Feedback目前不需要转换

2023-08-21 19:04 UTC, Serein207 commented on src/include/convertor.h
> +            // check 字面意识指是否签到，但是这里的 isChecked 指是否已参加？
isChecked表示是否已经签到，和后端接口返回的数据中isParticipate语义相同

2023-08-22 01:57 UTC, merged